# Generated by Django 4.0.5 on 2022-07-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'TODOS'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='TODO',
        ),
    ]
